[phases.setup]
nixPkgs = ['php81', 'composer', 'nodejs-18_x', 'php81Extensions.zip', 'php81Extensions.fileinfo', 'php81Extensions.mbstring']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'npm install'
]

[start]
cmd = 'npm run dev'
